**015017**
**UMANG DHAR DWIVEDI**
**HUGGING FACE PROJECTS**🤗
 

---




1.   **Sentiment Analysis**
2.   **ENGLISH - HINDI Translato**r
3.   A**utomated Text Generator**



In [ ]:
# Transformers installation
! pip install transformers



In [ ]:
from transformers import pipeline  # WE IMPORT PIPELINE FROM TRANSFORMERS, PIPELINE WILL BE CALLING A PRE TRAINED MODEL
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Now we will be checking weather the sentiments we possess are carried out by the system


In [ ]:
classifier('We are very happy .')   ##SHOULD HAVE A POSITIVE SENTIMET

[{'label': 'POSITIVE', 'score': 0.9998819828033447}]

In [ ]:
classifier('We are very SAD .')    ##SHOULD HAVE A NEGATIVE SENTIMENT

[{'label': 'NEGATIVE', 'score': 0.9988749623298645}]

In [ ]:
classifier("we have been waiting for last 3 hours") ##LET'S SEE IF WORKS SIMILARLY ON SITUATION ## SHOULD BE NEGATIVE 

[{'label': 'NEGATIVE', 'score': 0.9606083035469055}]

In [ ]:
classifier("we got the best seats")  ##SHOULD BE POSITIVE

[{'label': 'POSITIVE', 'score': 0.9997585415840149}]

In [ ]:
classifier = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

Downloading:   0%|          | 0.00/953 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/638M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/851k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [ ]:
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
# This model only exists in PyTorch, so we use the `from_pt` flag to import that model in TensorFlow.
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
classifier("I am a good boy")

[{'label': '4 stars', 'score': 0.42292699217796326}]

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tf_model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_57']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
inputs = tokenizer("We are very happy to show you the 🤗 Transformers library.")

In [ ]:
print(inputs)

{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [ ]:
tf_batch = tokenizer(
    ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf"
)

In [ ]:
for key, value in tf_batch.items():
    print(f"{key}: {value.numpy().tolist()}")

input_ids: [[101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 100, 19081, 3075, 1012, 102], [101, 2057, 3246, 2017, 2123, 1005, 1056, 5223, 2009, 1012, 102, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]


In [ ]:
tf_outputs = tf_model(tf_batch)

In [ ]:
print(tf_outputs)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.0832963 ,  4.3364143 ],
       [ 0.08181736, -0.04179246]], dtype=float32)>, hidden_states=None, attentions=None)


In [ ]:
import tensorflow as tf
tf_predictions = tf.nn.softmax(tf_outputs[0], axis=-1)

In [ ]:
print(tf_predictions)

tf.Tensor(
[[2.2042994e-04 9.9977952e-01]
 [5.3086317e-01 4.6913683e-01]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf
tf_outputs = tf_model(tf_batch, labels = tf.constant([1, 0]))

In [ ]:
tokenizer.save_pretrained('/content/drive/MyDrive/HUGGINGFACE')
model.save_pretrained('/content/drive/MyDrive/HUGGINGFACE')

In [ ]:
tf_outputs = tf_model(tf_batch, output_hidden_states=True, output_attentions=True)
all_hidden_states, all_attentions = tf_outputs[-2:]

In [ ]:
from transformers import DistilBertTokenizer, TFDistilBertForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFDistilBertForSequenceClassification.from_pretrained(model_name)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_77']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
config = DistilBertConfig(n_heads=8, dim=512, hidden_dim=4*512)
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = TFDistilBertForSequenceClassification(config)

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

In [ ]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
model_name = "distilbert-base-uncased"
model = TFDistilBertForSequenceClassification.from_pretrained(model_name, num_labels=10)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

Downloading:   0%|          | 0.00/347M [00:00<?, ?B/s]

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertForSequenceClassification: ['activation_13', 'vocab_transform', 'vocab_projector', 'vocab_layer_norm']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier', 'dropout_117', 'classifier']
You should probably TRAIN this model on a down-stream task to be able to use 

In [5]:
!pip install transformers -U -q

In [6]:
! pip install sentencepiece

In [7]:
!pip freeze | grep transformers

transformers==4.15.0


In [8]:
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast


In [9]:
model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-one-to-many-mmt")


In [10]:
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-one-to-many-mmt", src_lang="en_XX")


Downloading:   0%|          | 0.00/4.83M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/717 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/528 [00:00<?, ?B/s]

In [24]:
article_en = "MY NAME IS UMANG , this is my project"

In [25]:
model_inputs = tokenizer(article_en, return_tensors="pt")


In [26]:
# translate from English to Hindi
generated_tokens = model.generate(
    **model_inputs,
    forced_bos_token_id=tokenizer.lang_code_to_id["hi_IN"]
)



In [27]:
translation = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)


In [28]:
translation

['मेरा नाम उमांग है, यह मेरी परियोजना है']

In [2]:
 from transformers import pipeline

In [3]:
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')

Downloading:   0%|          | 0.00/200 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/779k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.0 [00:00<?, ?B/s]

In [15]:
text = generator(" Superman vs Batman is " , do_sample=True, min_length=500)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [16]:
text

[{'generated_text': " Superman vs Batman is  still the biggest issue and the main reason why i don't like it.\n\nA:\n\nIt was the second worst film of 2018.\nFor example, it had a lot of bad jokes, bad acting,"}]

In [17]:
print(text[0]['generated_text'])

 Superman vs Batman is  still the biggest issue and the main reason why i don't like it.

A:

It was the second worst film of 2018.
For example, it had a lot of bad jokes, bad acting,


In [18]:
text = generator("import pandas as pd \n import numpy as np\n " , do_sample=True, min_length=200)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [19]:
text

[{'generated_text': "import pandas as pd \n import numpy as np\n \n csv = pd.read_csv('../data/data-file1.csv')\n\n pd.options.display.max_columns = 100"}]

In [20]:
print(text[0]['generated_text'])

import pandas as pd 
 import numpy as np
 
 csv = pd.read_csv('../data/data-file1.csv')

 pd.options.display.max_columns = 100


In [21]:
text = generator("My name is Julien and I like to " , do_sample=True, min_length=200)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [22]:
text

[{'generated_text': 'My name is Julien and I like to \nbe the most efficient and accurate person who \ncovers the whole market."\n"The market is going through a really serious\ntransition right now," he says. "It\'s '}]

In [23]:
print(text[0]['generated_text'])

My name is Julien and I like to 
be the most efficient and accurate person who 
covers the whole market."
"The market is going through a really serious
transition right now," he says. "It's 


In [24]:
text = generator("My name is Umang, my favorite " , do_sample=True, min_length=200)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [25]:
text

[{'generated_text': "My name is Umang, my favorite ichthyologist at the aquarium in Klaipėda. I've been here for 18 weeks and my favorite species is the one that lives in a tank with only water, fish and sunlight."}]

In [26]:
print(text[0]['generated_text'])

My name is Umang, my favorite ichthyologist at the aquarium in Klaipėda. I've been here for 18 weeks and my favorite species is the one that lives in a tank with only water, fish and sunlight.
