**015017**
**UMANG DHAR DWIVEDI**
**HUGGING FACE PROJECTS**🤗
 

---




1.   **Sentiment Analysis**
2.   **ENGLISH - HINDI Translato**r
3.   A**utomated Text Generator**



****PART1 Sentiment Analysis****

In [39]:
# Transformers installation
! pip install transformers



In [40]:
from transformers import pipeline  # WE IMPORT PIPELINE FROM TRANSFORMERS, PIPELINE WILL BE CALLING A PRE TRAINED MODEL
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Now we will be checking weather the sentiments we possess are carried out by the system


In [41]:
classifier('We are very happy .')   ##SHOULD HAVE A POSITIVE SENTIMET

[{'label': 'POSITIVE', 'score': 0.9998819828033447}]

In [42]:
classifier('We are very SAD .')    ##SHOULD HAVE A NEGATIVE SENTIMENT

[{'label': 'NEGATIVE', 'score': 0.9988749623298645}]

In [43]:
classifier("we have been waiting for last 3 hours") ##LET'S SEE IF WORKS SIMILARLY ON SITUATION ## SHOULD BE NEGATIVE 

[{'label': 'NEGATIVE', 'score': 0.9606083035469055}]

In [44]:
classifier("we got the best seats")  ##SHOULD BE POSITIVE

[{'label': 'POSITIVE', 'score': 0.9997585415840149}]

In [45]:
classifier = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

In [46]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [47]:
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"

model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [48]:
classifier("I am a good boy")

[{'label': '4 stars', 'score': 0.42292699217796326}]

In [49]:
classifier("He is  a good teacher")

[{'label': '4 stars', 'score': 0.5031822919845581}]

In [52]:
classifier("Spiderman was the best movie")

[{'label': '5 stars', 'score': 0.8448800444602966}]

In [50]:
classifier("I don't like the movie")

[{'label': '2 stars', 'score': 0.4483273923397064}]

In [51]:
classifier("I hate the movie")

[{'label': '1 star', 'score': 0.7138820290565491}]

In [53]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tf_model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_57']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [54]:
inputs = tokenizer("We are very happy to be present here with you all.")

In [55]:
print(inputs)

{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2022, 2556, 2182, 2007, 2017, 2035, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [57]:
tf_batch = tokenizer(
    ["We are very happy to be present here with you all.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf"
)

In [58]:
for key, value in tf_batch.items():
    print(f"{key}: {value.numpy().tolist()}")

input_ids: [[101, 2057, 2024, 2200, 3407, 2000, 2022, 2556, 2182, 2007, 2017, 2035, 1012, 102], [101, 2057, 3246, 2017, 2123, 1005, 1056, 5223, 2009, 1012, 102, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]


In [59]:
tf_outputs = tf_model(tf_batch)

In [60]:
print(tf_outputs)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.290483  ,  4.6060257 ],
       [ 0.08181736, -0.04179246]], dtype=float32)>, hidden_states=None, attentions=None)


In [61]:
import tensorflow as tf
tf_predictions = tf.nn.softmax(tf_outputs[0], axis=-1)

In [62]:
print(tf_predictions)

tf.Tensor(
[[1.3684714e-04 9.9986315e-01]
 [5.3086317e-01 4.6913683e-01]], shape=(2, 2), dtype=float32)


In [63]:
import tensorflow as tf
tf_outputs = tf_model(tf_batch, labels = tf.constant([1, 0]))

In [66]:
tokenizer.save_pretrained('/content/drive/MyDrive/HUGGINGFACE') ##directory made to save in google drive
model.save_pretrained('/content/drive/MyDrive/HUGGINGFACE')

In [67]:
tf_outputs = tf_model(tf_batch, output_hidden_states=True, output_attentions=True)
all_hidden_states, all_attentions = tf_outputs[-2:]

In [68]:
from transformers import DistilBertTokenizer, TFDistilBertForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFDistilBertForSequenceClassification.from_pretrained(model_name)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_77']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [69]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
config = DistilBertConfig(n_heads=8, dim=512, hidden_dim=4*512)
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = TFDistilBertForSequenceClassification(config)

In [70]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
model_name = "distilbert-base-uncased"
model = TFDistilBertForSequenceClassification.from_pretrained(model_name, num_labels=10)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertForSequenceClassification: ['vocab_transform', 'activation_13', 'vocab_projector', 'vocab_layer_norm']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['dropout_117', 'classifier', 'pre_classifier']
You should probably TRAIN this model on a down-stream task to be able to use 

**PART 2 TRANSLATION ENGLISH TO HINDI**

In [71]:
!pip install transformers -U -q

In [72]:
! pip install sentencepiece

In [73]:
!pip freeze | grep transformers

sentence-transformers==2.1.0
transformers @ git+https://github.com/huggingface/transformers.git@6b655cc63fd7e8ec120d9c38321a286d04767db0


In [2]:
from transformers import MBartForConditionalGeneration, MBart50TokenizerFast


In [3]:
model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-one-to-many-mmt")


In [4]:
tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-one-to-many-mmt", src_lang="en_XX")


In [5]:
article_en = "MY NAME IS UMANG , this is my project"

In [6]:
model_inputs = tokenizer(article_en, return_tensors="pt")


In [7]:
# translate from English to Hindi
generated_tokens = model.generate(
    **model_inputs,
    forced_bos_token_id=tokenizer.lang_code_to_id["hi_IN"]  ##hi_IN is the code to convert into hindi 
)



In [8]:
translation = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)


In [9]:
translation

['मेरा नाम उमांग है, यह मेरी परियोजना है']

In [15]:
article_en = "I watched Spiderman last Saturday, it was no doubt one of the best movies. 3 spiderman on 1 screen was a delight expierence"

In [16]:
model_inputs = tokenizer(article_en, return_tensors="pt")

In [17]:
generated_tokens = model.generate(
    **model_inputs,
    forced_bos_token_id=tokenizer.lang_code_to_id["hi_IN"]  ##hi_IN is the code to convert into hindi 
)



In [18]:
translation = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)


In [19]:
translation

['मैंने पिछले शनिवार को स्पाइडरमैन देखा था, इसमें कोई संदेह नहीं कि यह सर्वश्रेष्ठ फिल्मों में से एक था. एक स्क्रीन पर 3 स्पाइडरमैन एक आनंद था']

PART 3 TEXT GENERATOR

In [4]:
 from transformers import pipeline

In [2]:
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')  ## Model can be called through hugging face library by copying the name of model from the library

In [3]:
text = generator(" Superman vs Batman is " , do_sample=True, min_length=500)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [5]:
text

[{'generated_text': ' Superman vs Batman is  an anime film made by Funimation from a script by Naoki Urasawa and Atsushi Kitamura which was released on July 27, 2010. The film is based on a character from the Japanese web site Comic Shop'}]

In [6]:
print(text[0]['generated_text'])

 Superman vs Batman is  an anime film made by Funimation from a script by Naoki Urasawa and Atsushi Kitamura which was released on July 27, 2010. The film is based on a character from the Japanese web site Comic Shop


In [7]:
text = generator("import pandas as pd \n import numpy as np\n " , do_sample=True, min_length=200)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [8]:
text

[{'generated_text': 'import pandas as pd \n import numpy as np\n \n # Setup the dataframe of features, and the model\n def make_dataset():\n      \n      # Create'}]

In [9]:
print(text[0]['generated_text'])

import pandas as pd 
 import numpy as np
 
 # Setup the dataframe of features, and the model
 def make_dataset():
      
      # Create


In [10]:
text = generator("My name is Julien and I like to " , do_sample=True, min_length=200)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [11]:
text

[{'generated_text': 'My name is Julien and I like to \nwork hard.\nMy goal is to make people smile.\nI like to make people laugh.\nI like to have a good time.\nAnd you know what?\nThe last thing'}]

In [12]:
print(text[0]['generated_text'])

My name is Julien and I like to 
work hard.
My goal is to make people smile.
I like to make people laugh.
I like to have a good time.
And you know what?
The last thing


In [13]:
text = generator("My name is Umang, my favorite " , do_sample=True, min_length=200)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [14]:
text

[{'generated_text': 'My name is Umang, my favorite ichthyao, and I’m here to teach.”\n\nUmang, a middle-aged man, is the director of the International Center for Ichthyology. He has'}]

In [15]:
print(text[0]['generated_text'])

My name is Umang, my favorite ichthyao, and I’m here to teach.”

Umang, a middle-aged man, is the director of the International Center for Ichthyology. He has


**THANKS**